# Generated by Django 4.1.6 on 2023-02-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_creation', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField()),
                ('active', models.BooleanField(verbose_name='The notice is active')),
                ('pin', models.BooleanField(verbose_name='The notice is pinned')),
            ],
        ),
    ]
